POST http://localhost:8080/events
Content-Type: application/json
Authentication: 

{
	"name": "USER 2: Test Event failed",
	"description": "No Description ...",
	"location": "thr",
	"due_date": "2006-01-02T15:04:05.000Z"
}