PUT http://localhost:8080/events/1
Content-Type: application/json

{
	"name": "Update Event (id: 1)",
	"description": "Update Description for first id...",
	"location": "thr",
	"due_date": "2025-01-02T15:04:05.000Z"
}